name: Automatisation des tests

on: push

jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Compilation et tests
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          ctest --output-on-failure  # Exécuter tous les tests et afficher les erreurs le cas échéant
